# Helper for generating the index.js
#
# Usage:
# $ ruby ./build_index.rb > index.js
#
#----------------------------------------------------------------------

import_lines = []
exports = []

files = Dir.glob("src/**/*.js")
files.each do |file_name|

  File.open(file_name).each do |line|
    line.match(/export default class (\w+)/) do |match|
      export_name = match.captures[0]
      import_lines.push "import #{export_name} from './#{file_name}';"
      exports.push export_name
    end

    file_exports = []
    line.match(/export class (\w+)/) do |match|
      export_name = match.captures[0]
      file_exports.push export_name
      exports.push export_name
    end

    line.match(/export function (\w+)/) do |match|
      export_name = match.captures[0]
      file_exports.push export_name
      exports.push export_name
    end

    if file_exports.any?
      import_lines.push "import {#{file_exports.join(', ')}} from './#{file_name}';"
    end
  end

end


buffer = "// AUTOGENERATED FILE\n// THIS TEXT HAS BEEN GENERATED USING THE HELPER build_index.rb\n\n"

buffer += import_lines.join("\n");
buffer += "\n\n"
buffer += "export {#{exports.join(', ')}};"
puts buffer
