# Helper for generating the index.js
#
# Usage:
# $ ruby ./build_index.rb > index.js
#
#----------------------------------------------------------------------

import_lines = []
classes = []

files = Dir.glob("src/**/*.js")
files.each do |file_name|

  File.open(file_name).each do |line|
    line.match(/export default class (\w+)/) do |match|
      class_name = match.captures[0]
      import_lines.push "import #{class_name} from './#{file_name}';"
      classes.push class_name
    end

    file_classes = []
    line.match(/export class (\w+)/) do |match|
      class_name = match.captures[0]
      file_classes.push class_name
      classes.push class_name
    end
    if file_classes.any?
      import_lines.push "import {#{file_classes.join(', ')}} from './#{file_name}';"
    end
  end

end


buffer = "// AUTOGENERATED FILE\n// THIS TEXT HAS BEEN GENERATED USING THE HELPER build_index.rb\n\n"

buffer += import_lines.join("\n");
buffer += "\n\n"
buffer += "export {#{classes.join(', ')}};"
puts buffer
